name: OLIVE Action

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      analyze-only:
        description: "분석만 수행 (아티팩트/코멘트 생략)"
        required: false
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
          
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  olive-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run OLIVE Action
        uses: kakao/olive-action@v1
        with:
          olive-token: ${{ secrets.OLIVE_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
